name: tampay_mobile
description: "Fintech app for TamPay"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  url_launcher: ^6.3.0
  pinput: ^5.0.0
  flutter_card_swiper: ^7.0.1
  onscreen_num_keyboard: ^1.0.4
  flutter_styled_toast: ^2.2.1
  flutter_launcher_icons: ^0.13.1
  riverpod: ^2.5.1
  flutter_native_splash: ^2.4.1
  lottie: ^3.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.6.0
  envied: ^0.5.4+1
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.0
  multiple_result: ^5.1.0
  get_it: ^7.7.0
  flutter_udid: ^3.0.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  pretty_dio_logger: ^1.1.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  envied_generator: ^0.5.4+1

flutter_native_splash:
    color: "#FFFFFF"
    android: true
    ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/sora/Sora-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/sora/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/sora/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/sora/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sora/Sora-Light.ttf
          weight: 500

flutter_launcher_icons:
    android: "app_launcher"
    ios: true
    remove_alpha_ios: true
    image_path: "assets/images/tampay_logo.png"
    min_sdk_android: 21